# Generated by Django 5.1.4 on 2024-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together={('base_currency', 'quote_currency', 'date')},
        ),
    ]
